services:
  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant_storage:/qdrant/storage #./qdrant_storage:/qdrant/storage:z
    ports:
      - "6335:6333"
  chainlit-app:
    build: 
      dockerfile: Dockerfile
    volumes:
      - ./model_weights:/ragondin/model_weights
      - ./data:/ragondin/data  # PDF data for RAG
    
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    
    depends_on:
      - qdrant

    
    command: >
      bash -c "
        uv run uvicorn api:app --host ${APP_HOST} --port ${APP_PORT} --reload
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]

volumes:
  qdrant_storage: