services:
  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant_storage:/qdrant/storage #./qdrant_storage:/qdrant/storage:z

  chainlit-app:
    build: 
      dockerfile: Dockerfile
    volumes:
      - ./model_weights:/app/model_weights
      - ./data:/app/data # PDF data for RAG
      - ./ragondin:/app/ragondin # RAG model
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    
    depends_on:
      - qdrant

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]

volumes:
  qdrant_storage: