defaults:
  - chunker: semantic_splitter
  - retriever: multiQuery
  - rag: ChatBotRag
  - llm: llama # lucie

embedder:
  type: huggingface
  model_name: HIT-TMG/KaLM-embedding-multilingual-mini-v1
  # powerful multilingual model => More language => token's decomposed heavily => More to embed => this model is better than Alibaba NLP models

vectordb:
  host: qdrant
  port: 6333
  connector_name: qdrant
  collection_name: vdb95 # vdb95_no_context
  hybrid_mode: true

reranker:
  model_name: jinaai/jina-colbert-v2
  top_k: 7

grader:
  grade_documents: true

verbose:
  verbose: true
  level: INFO

paths:
  root_dir: ${oc.env:ROOT_DIR}
  base_dir: ${oc.env:BASE_DIR}
  prompts_dir: ${oc.env:PROMPTS_DIR}

prompt:
  rag_sys_pmpt: rag_sys_prompt_template.txt # rag_sys_pmpt_tmpl_ifa.txt
  context_pmpt_tmpl: contextualize_prompt_template.txt